<?php
/**
 * Contains class.
 *
 * PHP version 5
 *
 * Copyright (c) ${YEAR}, Mike Pretzlaw
 * All rights reserved.
 *
 * @category  LeMike_DevMode
 * @package   Template
 * @author    Mike Pretzlaw <pretzlaw@gmail.com>
 * @copyright 2013 Mike Pretzlaw
 * @license   http://github.com/sourcerer-mike/${PROJECT_NAME}/blob/master/License.md BSD 3-Clause ("BSD New")
 * @link      http://github.com/sourcerer-mike/${PROJECT_NAME}
 * @since     ${DS}VERSION${DS}
 *
 * @var LeMike_DevMode_Block_Toolbox $this
 */

?>
<ul>
    <li>
        <a href="<?php echo $this->getBackendUrl() ?>">
            <span class="blind"><?php echo $this->__('Goto backend'); ?></span>
        </a>
    </li>
    <li>
        <a href="#" onclick="lemikeDevmode_alert('ld_toolbox_layouts', 'Layouts')">
            <span class="blind">
                <?php echo $this->__('List all layout Handles'); ?>
            </span>
        </a>
    </li>
    <li>
        <a href="<?php echo $this->getUrl('lemike_devmode/toolbox/clearCache') ?>">
            <span class="blind"><?php echo $this->__('Clear cache'); ?></span>
        </a>
    </li>
    <li>
        <a href="#"
           onclick="lemikeDevmode_showEvents()"
           title="<?php echo $this->__('List thrown events with their observer'); ?>">
            <span class="blind">
                <?php echo $this->__('Events and observer'); ?>
            </span>
        </a>
    </li>
    <li>
        <a href="?<?php echo $this->getConfigSwitchQuery('dev/translate_inline/active'); ?>"
           title="<?php echo $this->__('List thrown events with their observer'); ?>">
            <span class="blind">
                <?php if (Mage::app()->getStore()->getConfig('dev/translate_inline/active')): ?>
                    <?php echo $this->__('Exit translation'); ?>
                <?php else: ?>
                    <?php echo $this->__('Change translation'); ?>
                <?php endif; ?>
            </span>
        </a>
    </li>
</ul>
