language: php
php:
  - 5.3
env:
  - MAGE=1.7.0.2
before_script:
  # Setup
  - MAGE_DIR=tests/magento
  - DB=lemike_devmode_${MAGE//./}
  - BASE=http://magento.local/
  - CURRENT_DIR=$(pwd)
  # Install magento
  - ./n98-magerun.phar install --magentoVersionByName="magento-ce-$MAGE" --installationFolder=$MAGE_DIR --dbHost="localhost" --dbUser="root" --dbPass="" --dbName=$DB --installSampleData=yes --baseUrl=$BASE --useDefaultConfigParams=yes
  # Copying travis composer.json to test only module
  - cp -f .travis/composer.json composer.json
  # Installing required composer packages
  - composer update --dev
  # Installing LeMike_DevMode module
  - modman init $MAGE_DIR
  - ln -s $(pwd) $(pwd)/$MAGE_DIR/.modman/LeMike_DevMode
  # Installing EcomDev_PHPUnit module
  - git clone git://github.com/sourcerer-mike/EcomDev_PHPUnit.git -b dev-lemike ./phpunit/
  - ln -s $(pwd)/phpunit $(pwd)/$MAGE_DIR/.modman/phpunit
  - $MAGE_DIR/modman deploy-all
  # Configuring EcomDev_PHPUnit module
  - cd tests/magento/shell
  - php ecomdev-phpunit.php -a magento-config --db-name $DB --same-db 1 --base_url http://test.magento.com/
  - cd $CURRENT_DIR
script:
  - cd tests/magento
  - phpunit --stop-on-failure --colors --coverage-text -d display_errors=1 app/code/community/LeMike/DevMode/Test
