language: php
php:
  - 5.3
env:
  - MAGE=1.7.0.2
before_install:
  # Setup
  - MAGE_DIR=tests/magento
  - DB=lemike_devmode_${MAGE//./}
  - BASE=http://magento.local/
  - CURRENT_DIR=$(pwd)
  # Get n98
  - wget https://raw.github.com/netz98/n98-magerun/master/n98-magerun.phar
install:
  # Install magento
  - php n98-magerun.phar install --magentoVersionByName="magento-ce-${MAGE}" --installationFolder=${MAGE_DIR} --dbHost="localhost" --dbUser="root" --dbPass="" --dbName=${DB} --baseUrl=${BASE} --useDefaultConfigParams=yes --installSampleData=no
  # Installing LeMike_DevMode module
  - modman init $MAGE_DIR
  - ln -s $(pwd) $(pwd)/.modman/LeMike_DevMode
  # Installing EcomDev_PHPUnit module
  - modman clone git://github.com/sourcerer-mike/EcomDev_PHPUnit.git -b dev-lemike
  - modman deploy-all
  # Configuring EcomDev_PHPUnit module
  - cd tests/magento/shell
  - php ecomdev-phpunit.php -a magento-config --db-name $DB --same-db 1 --base-url http://test.magento.com/
  - cd $CURRENT_DIR
script:
  - cd tests/magento
  - phpunit --stop-on-failure --colors --coverage-text -d display_errors=1 app/code/community/LeMike/DevMode/Test
