language: php
php:
  - 5.3
  - 5.4
env:
  - MAGE=1.7.0.2
before_script:
  - MAGE_DIR=tests/magento
  # Fixing Magento hackathon installer
  - mkdir -p $MAGE_DIR
   # Copying travis composer.json to test only module
  - cp -f .travis/composer.json composer.json
  # Installing required composer packages
  - composer update --dev
  # Installing magento version with prepared DB dump
  - bin/mage-ci install $MAGE_DIR $MAGE magento -c -t -r http://mage-ci.ecomdev.org
  # Installing LeMike_DevMode module
  - bin/mage-ci install-module tests/magento $(pwd)
  # Installing EcomDev_PHPUnit module
  - git clone git://github.com/sourcerer-mike/EcomDev_PHPUnit.git -b dev-lemike ./phpunit/
  - bin/mage-ci install-module tests/magento "$(pwd)/phpunit/"
  # Configuring EcomDev_PHPUnit module
  - CURRENT_DIR=$(pwd)
  - cd tests/magento/shell
  - php ecomdev-phpunit.php -a magento-config --db-name magento --same-db 1 --base_url http://test.magento.com/
  - cd $CURRENT_DIR
script:
  - bin/mage-ci phpunit tests/magento --colors --coverage-text -d display_errors=1 app/code/community/LeMike/DevMode/Test
