<?php
/**
 * Contains class.
 *
 * PHP version 5
 *
 * Copyright (c) ${YEAR}, Mike Pretzlaw
 * All rights reserved.
 *
 * @category  LeMike_DevMode
 * @package   Template
 * @author    Mike Pretzlaw <pretzlaw@gmail.com>
 * @copyright 2013 Mike Pretzlaw
 * @license   http://github.com/sourcerer-mike/${PROJECT_NAME}/blob/master/License.md BSD 3-Clause ("BSD New")
 * @link      http://github.com/sourcerer-mike/${PROJECT_NAME}
 * @since     0.3.0
 */

?>
<script type="text/javascript">
    function devmode_Customer_Customer_DeleteAll() {

        var message = 'This will reset all customer!\n'
            + 'After this operation every customer is deleted.\n'
            + 'This might affect orders and addresses.\n'
            + '\n'
            + 'Are you sure to delete all customer?';

        if (confirm(message)) {
            new Ajax.Request(
                "<?php echo $this->getUrl('adminhtml/developer_customer_customer/deleteAll') ?>",
                {
                    onSuccess: function (response) {
                        alert(response.responseJSON.processed
                            + " of "
                            + response.responseJSON.amount
                            + " have been deleted.");
                }
            });
        }
    }
</script>
