<?php /** @var LeMike_DevMode_Block_Core_Resource $this */ ?>
<h2><?php echo $this->__('Resource'); ?></h2>

<table border="1">
    <thead>
    <tr>
        <th><?php echo $this->__('Name'); ?></th>
        <th><?php echo $this->__('Cached version'); ?></th>
        <th><?php echo $this->__('Installed version'); ?></th>
        <th><?php echo $this->__('Filesystem version'); ?></th>
        <th><?php echo $this->__('Code pool'); ?></th>
        <th><?php echo $this->__('Action'); ?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->getModuleSet() as $data): ?>
        <?php
        /** @var Varien_Object $data */
        $moduleName = $data->getData(LeMike_DevMode_Model_Core_Resource::MODULE_NAME);
        $databaseVersion = $data->getData(
                                LeMike_DevMode_Model_Core_Resource::MODULE_VERSION_DATABASE
        );

        /** @var Mage_Adminhtml_Helper_Data $helperAdminhtml */
        $helperAdminhtml = Mage::helper('adminhtml');

        /** @var string $runSetup */
        $runSetup   = $helperAdminhtml->getUrl(
            'lemike_devmode/adminhtml_developer_core/run',
            array(LeMike_DevMode_Helper_Params::CORE_INDEX__SETUP_MODULE_NAME => $moduleName)
        );
        ?>
        <tr>
            <td>
                <?php echo $moduleName ?></td>
            <td>
                <?php echo $data->getData(
                                LeMike_DevMode_Model_Core_Resource::MODULE_VERSION_CACHED
                ) ?>
            </td>
            <td>
                <?php echo $databaseVersion ?></td>
            <td>
                <?php echo $data->getData(
                                LeMike_DevMode_Model_Core_Resource::MODULE_VERSION_CONFIG
                ) ?>
            </td>
            <td>
                <?php echo $data->getData(LeMike_DevMode_Model_Core_Resource::MODULE_CODE_POOL) ?>
            </td>
            <td>
                <?php if (strpos($moduleName, 'Mage_Admin') === 0): ?>
                    <span><?php echo $this->__('not allowed'); ?></span>
                <?php elseif (!$databaseVersion): ?>
                    <span><?php echo $this->__('no installer'); ?></span>
                <?php else: ?>
                    <a href="<?php echo $runSetup ?>">
                        <?php echo $this->__('Run setup again'); ?>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
