<div class="content-header">
    <h2><?php echo $this->__('About LeMike_DevMode'); ?></h2>

    <p>The development tool for Magento.</p>
</div>
<div>
    <p>
        The purpose is to help you develop stores with Magento.<br />
    </p>

    <p>
        Warning! This extension is only ment for development and can be a security issue when using it in your online
        / live / productive shop.
    </p>

    <p>
    &copy; 2013 by Mike Pretzlaw
    </p>

    <hr />

    <h2><?php echo $this->__('Other helpful extensions'); ?></h2>

    <p>
        <?php echo $this->__('Those are further extension that help you develop:'); ?>
    </p>

    <ul>
        <li>http://github.com/fbrnc/Aoe_TemplateHints</li>
        <li>http://magicento.com</li>
    </ul>

    <p>
        <?php echo $this->__('If you do not develop magento with the phpStorm IDE you probably are slow.'); ?>
        <?php echo $this->__('Got some other helpful extensions? Please mail to mike@code-x.de .'); ?>
    </p>
</div>
