<div class="content-header">
    <h2><?php echo $this->__('About LeMike_DevMode'); ?></h2>

    <p>The development tool for Magento.</p>
</div>
<div>
    <p>
        The purpose is to help you develop stores with Magento.<br />
    </p>

    <p>
        Warning! This extension is only ment for development and can be a security issue when using it in your online
        / live / productive shop.
    </p>

    <p>
    &copy; 2013 by Mike Pretzlaw
    </p>
</div>
