<?php

$file = $argv[1];

if (!$file)
{
    $file = '../../dev/codeSniffer.xml';
}

if (!file_exists($file))
{
    exit("File $file not found!" . PHP_EOL);
}

$doc = new DOMDocument();
$doc->loadXML(file_get_contents($file));

$xpath = new DOMXPath($doc);

$text = "";
$textContent = ltrim($doc->getElementsByTagName('description')->item(0)->textContent);
$text .= str_replace("\n        ", "\n", rtrim($textContent));
$text .= "\n\n";

$text .= "Note: This file is generated by using " . basename($file) . "
Everything you change will be lost after the next engender!

";


foreach ($xpath->query('//comment()') as $comment)
{
    $content = $comment->textContent;

    if (substr($content, 0, 1) != '-')
    { // no opener: not a doc-comment
        continue;
    }

    // remove opener
    $content = substr($content, 1);

    if (ltrim(substr($content, 0, 1), ' ') != "\n"
        && strpos($content, "\n") === false)
    { // single line
        // remove single space at beginning
        $content = substr($content, 1);
        // add line break in the end
        $content .= "\n";

        if (substr($content, 0, 1) == '#')
        { // is heading: add line to have one empty below it
            $content .= "\n";
        }
    }
    else
    { // comment block
        // replace indent
        $content = str_replace("\n    ", "\n", $content);
    }

    // remove disturbing line breaks at beginning:
    $content = ltrim($content, "\r\n");
    $text .= $content;
}

echo $text;
file_put_contents('codingStandards.md', $text);
