<?php

/** @var LeMike_DevMode_Block_Toolbox $this */

?>

<div class="lemike_devmode">
    <div id="ld_toolbox" class="ld_toolbox">
    <strong class="title">TOOLBOX</strong>
        <?php echo $this->getChildHtml() ?>
        <div class="section">
            <em>General</em>
            <ul>
                <li>
                    <a href="<?php echo $this->getBackendUrl() ?>">
                        <span class="blind"><?php echo $this->__('Goto backend'); ?></span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

<script>
    var toolboxId = "#ld_toolbox";


    jQuery(function () {

        var toolbox = jQuery(toolboxId);

        toolbox.css('position', 'absolute');
        toolbox.offset({ top: 100, left: 10});

        toolbox.draggable();
    });

</script>
