<?php
/**
 * Contains class.
 *
 * PHP version 5
 *
 * Copyright (c) ${YEAR}, Mike Pretzlaw
 * All rights reserved.
 *
 * @category  LeMike_DevMode
 * @package   Template
 * @author    Mike Pretzlaw <pretzlaw@gmail.com>
 * @copyright 2013 Mike Pretzlaw
 * @license   http://github.com/sourcerer-mike/${PROJECT_NAME}/blob/master/License.md BSD 3-Clause ("BSD New")
 * @link      http://github.com/sourcerer-mike/${PROJECT_NAME}
 * @since     ${DS}VERSION${DS}
 *
 * @var LeMike_DevMode_Block_Core_Php $this
 */

?>
    <h2><?php echo $this->__('PHP'); ?></h2>

<?php echo $this->getPhpInfo();
