<?php
/**
 * JavaScript for backend catalog operations.
 *
 * PHP version 5
 *
 * Copyright (c) ${YEAR}, Mike Pretzlaw
 * All rights reserved.
 *
 * @category  LeMike_DevMode
 * @package   Template
 * @author    Mike Pretzlaw <pretzlaw@gmail.com>
 * @copyright 2013 Mike Pretzlaw
 * @license   http://github.com/sourcerer-mike/${PROJECT_NAME}/blob/master/License.md BSD 3-Clause ("BSD New")
 * @link      http://github.com/sourcerer-mike/${PROJECT_NAME}
 * @since     ${DS}VERSION${DS}
 */

?>
<script type="text/javascript">
    function devmode_Catalog_Products_DeleteAll() {
        if (confirm('This will delete all products forever!\nAfter this operation every product is gone.\nThis will affect orders too.\n\nAre you sure to delete all products?')) {

            new Ajax.Request("<?php echo $this->getUrl('adminhtml/developer_catalog_products/deleteAll') ?>", {
                onSuccess: function (response) {
                    alert(response.responseJSON.processed + " of " + response.responseJSON.amount + " have been deleted.");
                }
            });
        }
    }

    function devmode_Catalog_Products_SanitizeAll() {
        if (confirm('This will reset all products stock!\nAfter this operation every product is set to zero.\nThis might affect new orders.\n\nAre you sure to sanitize all product stocks?')) {

            new Ajax.Request("<?php echo $this->getUrl('adminhtml/developer_catalog_products/sanitizeAll') ?>", {
                onSuccess: function (response) {
                    alert(response.responseJSON.processed + " of " + response.responseJSON.amount + " have been sanitized.");
                }
            });
        }
    }
</script>
