<script type="text/javascript">
    function devmode_Catalog_Products_DeleteAll() {
        if (confirm('This will delete all products for ever!\nAfter this operation every product is gone.\nThis will affect orders too.\n\nAre you sure to delete all products?')) {

            new Ajax.Request("<?php echo $this->getUrl('adminhtml/developer_catalog_products/deleteAll') ?>", {
                onSuccess: function (response) {
                    eval("json = " + response.responseText);
                    alert(json.deleted + " of " + json.before + " have been deleted.");
                }
            });
        }
    }
</script>
